# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eeb0372e439a1823e0640252da7067e306bb16ed4ac57e7758da5949a4bab38911d3e82e42f88f226b2c6bfa9ea44cedecfa8bd439ac271087c270d965c6b87

test:
  secret_key_base: 2ee1d4ed8b6341046abd027865552266145d4804d077581099f77916dd316eb3cb4cf727c2bdd33fadc0d0f04759a72242f22604d64034179dbc0ee958e66929

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
